name: RxSwift

on: [push, pull_request]

jobs:
  cocoa:
    name: "Test"
    runs-on: macOS-latest
    
    strategy:
      matrix:
        environment: [iOS, iOS-Example, Unix, watchOS, tvOS, SPM]

    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Run Tests
        run: CI=1 ./scripts/all-tests.sh "${{ matrix.environment }}"

  specs:
    name: "CocoaPods Spec Test"
    runs-on: macOS-latest

    strategy:
      matrix:
        target: [RxSwift, RxCocoa, RxRelay, RxBlocking, RxTest]

    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Test Specs
        run: CI=1 TARGET=${{ matrix.target }} SWIFT_VERSION=5.3 ./scripts/validate-podspec.sh

  linux:
    name: "Test (Linux)"
    runs-on: ubuntu-16.04

    steps:
    - name: Swift 5.3 Docker Container
      uses: docker://swift:5.3-xenial
    - uses: actions/checkout@v2
    - name: Run tests
      run: CI=1 ./scripts/all-tests.sh "Unix"